### ISSUE TITLE
Looks like setting buttons color does not work

### ISSUE THREAD

**Issue by ivan133** [thebylito/react-native-navigation-bar-color#3] opened 2018-05-29 09:36 UTC
I'm trying to set white natigation bar color with dark buttons:

```
import changeNavigationBarColor from 'react-native-navigation-bar-color';
...
changeNavigationBarColor('#ffffff', false);
```

But looks like it does not work - the buttons are always white.
![screenshot_1527586464](https://user-images.githubusercontent.com/4018236/40650730-a42075dc-633c-11e8-9e7e-1c83b8ccf5d3.png)

Just in case I've tried to set changeNavigationBarColor('#ffffff', true); 
Nothing changed.

I've tested it on androids from 6 to 8.

**Comment by thebylito** [comment] 2018-05-29 10:41
hi, "#ffffff" is white :)

try changeNavigationBarColor('#000000', true);

**Comment by thebylito** [comment] 2018-05-29 11:35
Ah yes. This is the result that should be expected.
I just did a test and it worked as expected.

When it set to white, did it work as expected? the problem is just the same buttons?

**Comment by ivan133** [comment] 2018-05-29 11:37
Yes, the problem is the button color for me they did not change color no matter what I pass as the second argument.

**Comment by thebylito** [comment] 2018-05-29 11:46
Please, let me see your package version in package.json

**Comment by ivan133** [comment] 2018-05-29 12:05
Sure 

  "dependencies": {
    "react": "^16.3.0",
    "react-native": "^0.55.0",
    "react-native-appsflyer": "1.1.9",
    "react-native-document-scanner": "^1.4.1",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-meteor": "^1.2.0",
    "react-native-navigation-bar-color": "0.0.6",
    "react-native-onesignal": "github:BlackTies/react-native-onesignal#7ecedccf20a26fc9ce8a5d9ff44c7fb57bfd2e17",
    "react-native-smart-splash-screen": "^2.3.5",
    "react-native-vector-icons": "^4.4.2",
    "react-native-webview-android": "github:pmogollons/react-native-webview-android#209fa6f6f2a9ccb0d84a0302836c95ece3ebcef3",
    "react-native-wkwebview-reborn": "^1.16.0"
  },

**Comment by thebylito** [comment] 2018-05-29 12:21
ok, i'm work in this

**Comment by ivan133** [comment] 2018-06-07 18:20
Hi! Any news about this one?

**Comment by thebylito** [comment] 2018-06-07 18:27
Take a test: not setting to light when setting the color, maybe solve.
`changeNavigationBarColor('#000000');`

**Comment by IRDeNial** [comment] 2018-10-12 22:44
There you guys go.
Pull request #6

**Comment by thebylito** [comment] 2018-10-13 01:56
Nice, please test merged version,
npm i -s react-native-navigation-bar-color@0.0.8

**Comment by jeodiong** [comment] 2018-10-14 10:51
"react-native-navigation-bar-color": "^0.0.8" still not working

**Comment by IRDeNial** [comment] 2018-10-14 14:33
What version of Android are you testing on and what code are you using to
test?

**Comment by thebylito** [comment] 2018-10-14 16:50
> I'm trying to set white natigation bar color with dark buttons:
> 
> ```
> import changeNavigationBarColor from 'react-native-navigation-bar-color';
> ...
> changeNavigationBarColor('#ffffff', false);
> ```
> But looks like it does not work - the buttons are always white.
> ![screenshot_1527586464](https://user-images.githubusercontent.com/4018236/40650730-a42075dc-633c-11e8-9e7e-1c83b8ccf5d3.png)
> 
> Just in case I've tried to set changeNavigationBarColor('#ffffff', true);
> Nothing changed.
> 
> I've tested it on androids from 6 to 8.

Tested and working:

![image](https://user-images.githubusercontent.com/29806253/46919604-96247c00-cfaf-11e8-996a-81330dad6562.png)

"react-native-navigation-bar-color": "^0.0.8"
changeNavigationBarColor('#ffffff', true);

**Comment by jeodiong** [comment] 2018-10-17 01:43
it works when I remove 
`<StatusBar barStyle="dark-content" backgroundColor="white" /> `

**Comment by jeodiong** [comment] 2018-10-17 01:47
but I need StatusBar in dark-content, they can not work the same time now

**Comment by jeodiong** [comment] 2018-10-17 01:54
add
`setTimeout(() => {
  changeNavigationBarColor('white', true);
}, 1000);`
works fine

**Comment by IRDeNial** [comment] 2018-10-17 17:18
That might be an issue directly related to your code then, especially if
it's working when you delay setting the navigation bar color.

**Comment by jeodiong** [comment] 2018-10-18 06:10
tried with new project, it comes again
maybe you can try add 
`changeNavigationBarColor('white', true);`
`<StatusBar barStyle="dark-content" backgroundColor="white" />`
the same time, you may facing the same problem

**Comment by IRDeNial** [comment] 2018-10-18 17:47
@jeodiong Why not just style your StatusBar accordingly instead of expecting something that's not targeting the statusbar to do it?
That just confirms that the issue is on your end.

You might wanna open up a separate issue for that since this was resolved.

**Comment by IRDeNial** [comment] 2018-11-09 18:35
Closing due to inactivity and confirmation of issue being resolved by others.

**Closed by IRDeNial** 2018-11-09 18:35 UTC

**Comment by dtroydev** [comment] 2023-02-26 02:41
On API 33 if theme is changed (ie. light to dark or dark to light), while the app is open in the background, the navigation bar color scheme isn't being picked up as far as button foreground color is concerned when the app is brought to foreground... (I think this behaviour likely started with API 30+ because that's when SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR got deprecated)

When I update setNavigationBarTheme function as follows it seems to work better (ie. app picks up light <-> dark theme changes as far as button color is concerned without needing to be restarted):

```
 public void setNavigationBarTheme(Activity activity, Boolean light) {
        if (activity != null && Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            Window window = activity.getWindow();
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                int flags = window.getDecorView().getSystemUiVisibility();            
                if (light) {
                    flags |= View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
                } else {
                    flags &= ~View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
                }
                window.getDecorView().setSystemUiVisibility(flags);
            } 
            else {
                WindowInsetsController insetsController = window.getInsetsController();
                if (light) {
                    insetsController.setSystemBarsAppearance(
                        WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,
                        WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS
                    );
                }
                else {
                    insetsController.setSystemBarsAppearance(
                        0,
                        WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS
                    );
                }
            }
        }
    }
```
Maybe it's worthwhile updating the package with something similar to the above ?

**Comment by bimix** [comment] 2023-11-22 08:24
> On API 33 if theme is changed (ie. light to dark or dark to light), while the app is open in the background, the navigation bar color scheme isn't being picked up as far as button foreground color is concerned when the app is brought to foreground... (I think this behaviour likely started with API 30+ because that's when SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR got deprecated)
> 
> When I update setNavigationBarTheme function as follows it seems to work better (ie. app picks up light <-> dark theme changes as far as button color is concerned without needing to be restarted):
> 
> ```
>  public void setNavigationBarTheme(Activity activity, Boolean light) {
>         if (activity != null && Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
>             Window window = activity.getWindow();
>             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
>                 int flags = window.getDecorView().getSystemUiVisibility();            
>                 if (light) {
>                     flags |= View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
>                 } else {
>                     flags &= ~View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
>                 }
>                 window.getDecorView().setSystemUiVisibility(flags);
>             } 
>             else {
>                 WindowInsetsController insetsController = window.getInsetsController();
>                 if (light) {
>                     insetsController.setSystemBarsAppearance(
>                         WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,
>                         WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS
>                     );
>                 }
>                 else {
>                     insetsController.setSystemBarsAppearance(
>                         0,
>                         WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS
>                     );
>                 }
>             }
>         }
>     }
> ```
> 
> Maybe it's worthwhile updating the package with something similar to the above ?

where the hell did you even find setNavigationBarTheme ?
